---
title: "HW_4_Jake_Nyiri"
author: "Jake Nyiri"
date: "11/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
library(tidyverse)
library(lubridate)
library(broom)
library(here)
library(effsize)

raw_hare_data <- read.csv(here("Data","bonanza_hares.csv"))

```

```{r}
#Create a base dataframe of just the juvenile rabbits with year info pulled out 
juvenile_hare_data <- raw_hare_data %>% 
  mutate(date = mdy(date)) %>% 
  mutate(year = year(date)) %>% 
  
  filter(age == "j")

levels(juvenile_hare_data$sex)[levels(juvenile_hare_data$sex)=="f"] <- "Female"
levels(juvenile_hare_data$sex)[levels(juvenile_hare_data$sex)=="m"] <- "Male"

#revalue(juvenile_hare_data, c("f" = "female", "m"="male"))

#Create second base dataframe with NA values removed from female and male rabbits weight
juvenile_hare_data_no_NA <- juvenile_hare_data %>% 
  filter(weight != "NA" & sex != "NA")
```

```{r}
#Part 1 of assignment-
#Count juvenile hares only trapped for each year
juvenile_trap_data <- juvenile_hare_data %>% 
  
  group_by(year) %>% 
  summarize(
    number_trapped = n(),
    )
juvenile_trap_data

trapped_mean <- mean(juvenile_trap_data$number_trapped)
trapped_median <- median(juvenile_trap_data$number_trapped)

```
```{r}
first_juvenile_plot <- juvenile_trap_data %>% 
  ggplot(aes(x=year, y=number_trapped))+
  geom_col()

first_juvenile_plot
```

```{r}
#Second part of assignment
#Compare juv hare weights by sex for each site

juv_weights_plot <- juvenile_hare_data %>% 
  
  group_by(grid) %>% 
  ggplot(aes(x=grid, y=weight))+
  geom_point()+
  facet_wrap(~sex)

juv_weights_plot
```

```{r}
#Third part of assignment
#compare stats for male and female juvenile snowshoe hares
#Then run t-test and Cohen's

bunny_sex_compare <- juvenile_hare_data_no_NA %>% 
  group_by(sex) %>% 
  summarize(
    mean_weight = mean(weight),
    sd_weight = sd(weight),
    number_trapped = n())

bunny_sex_compare
```
```{r, include = FALSE}
#Check the assumptions of the rabbit data before trying a t-test
#Don't include in final markdown document
bunny_normal_test<-juvenile_hare_data_no_NA %>% 
  ggplot(aes(sample=weight))+
  geom_qq(aes(color=sex))

bunny_normal_test
#Not the best but close enough

```

```{r}
#Run tests (t-test and cohens d)
#First need to pull out weights by sex

female_weights <- juvenile_hare_data_no_NA %>% 
  filter(sex=="Female") %>% 
  pull(weight)

male_weights <- juvenile_hare_data_no_NA %>% 
  filter(sex=="Male") %>% 
  pull(weight)

bunny_t_test <- t.test(female_weights,male_weights)
bunny_t_test

bunny_cohen <- cohen.d(female_weights, male_weights)
bunny_cohen

```

```{r}
juvenile_hare_ft_and_weight <- juvenile_hare_data_no_NA %>% 
  filter(hindft != "NA")

foot_weight_plot<- juvenile_hare_ft_and_weight %>% 
  ggplot(aes(x=weight, y=hindft))+
  geom_point()

foot_weight_plot

```

